import "./categorie.css";
import Input from "./Input";

function Category({ handleChange }) {
  return (
    <div>
      <h2 className="sidebar-title">Category</h2>

      <div>
        
        <Input
          handleChange={handleChange}
          value=""
          title="All"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="smartphones"
          title="smartphones"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="laptops"
          title="laptops"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="fragrances"
          title="fragrances"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="skincare"
          title="skincare"
          name="test"
        />
         <Input
          handleChange={handleChange}
          value="groceries"
          title="groceries"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="furniture"
          title="furniture"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="tops"
          title="tops"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="womens-dresses"
          title="womens-dresses"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="womens-shoes"
          title="womens-shoes"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="mens-shirts"
          title="mens-shirts"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="mens-shoes"
          title="mens-shoes"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="mens-watches"
          title="mens-watches"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="womens-watches"
          title="womens-watches"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="womens-bags"
          title="womens-bags"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="womens-jewellery"
          title="womens-jewellery"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="sunglasses"
          title="sunglasses"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="automotive"
          title="automotive"
          name="test"
        />
        <Input
          handleChange={handleChange}
          value="motorcycle"
          title="motorcycle"
          name="test"
        />
         <Input
          handleChange={handleChange}
          value="lighting"
          title="lighting"
          name="test"
        />
      </div>
    </div>
  );
}

export default Category;
